apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  namespace: llm-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
        - name: pytorch
          image: srideviwijaya/pytorch-poc:latest
          resources:
            limits:
              nvidia.com/gpu: 1
          args: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /mnt
              name: poc-store
            - mountPath: /.cache
              name: cache-store
      volumes:
        - name: poc-store
          persistentVolumeClaim:
            claimName: poc-store
        - name: cache-store
          persistentVolumeClaim:
            claimName: cache-store